[tool.poetry]
name = "marker"
version = "0.1.0"
description = ""
authors = ["Vik Paruchuri <vik.paruchuri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scikit-learn = "^1.3.2"
Pillow = "^10.1.0"
pytesseract = "^0.3.10"
PyMuPDF = "^1.23.5"
pymupdf-fonts = "^1.0.5"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
nougat-ocr = "^0.1.17"
transformers = "^4.34.1"
numpy = "^1.26.1"
python-dotenv = "^1.0.0"
torch = "^2.1.1"
ray = "^2.7.1"
tqdm = "^4.66.1"
tabulate = "^0.9.0"
thefuzz = "^0.20.0"
python-magic = "^0.4.27"
pyspellchecker = "^0.7.2"
ftfy = "^6.1.1"
nltk = "^3.8.1"
ocrmypdf = "^15.4.0"
bitsandbytes = "^0.41.2.post2"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
